# Generated by Django 4.2.16 on 2024-11-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(editable=False, max_length=40)),
                ('message', models.TextField(blank=True, editable=False)),
                ('diff', models.TextField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Committer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('initial_contact_date', models.DateTimeField(auto_now_add=True, verbose_name='initial contact date')),
                ('last_contact_date', models.DateTimeField(auto_now=True, verbose_name='date of last contact')),
                ('consent_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='date of consent')),
                ('opt_out', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date of opt-out')),
                ('initial_survey_response', models.TextField(blank=True, editable=False, null=True, verbose_name='response to initial survey')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(editable=False, max_length=200, verbose_name='project owner')),
                ('name', models.CharField(editable=False, max_length=200, verbose_name='project name')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='project add date')),
                ('remove_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='project remove date')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_response', models.TextField(editable=False)),
                ('commit', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.commit')),
                ('committer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.committer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_project_name'),
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.project'),
        ),
    ]
