# Generated by Django 4.2.16 on 2024-11-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='is_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
