# Generated by Django 4.2.16 on 2024-11-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_commit_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='installation_id',
            field=models.IntegerField(default=1, editable=False, verbose_name='installation ID'),
            preserve_default=False,
        ),
    ]
