# Generated by Django 4.2.16 on 2024-11-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_project_installation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='installation_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='installation ID'),
        ),
    ]
