# Generated by Django 4.2.16 on 2024-11-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_project_installation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committer',
            name='initial_survey_response',
        ),
        migrations.CreateModel(
            name='ProjectCommitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_survey_response', models.TextField(blank=True, editable=False, null=True, verbose_name='response to initial survey')),
                ('committer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.committer')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectcommitter',
            constraint=models.UniqueConstraint(fields=('project', 'committer'), name='unique_project_committer'),
        ),
    ]
