# Generated by Django 4.2.16 on 2024-11-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_committer_initial_survey_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='committer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.projectcommitter'),
        ),
    ]
