# Generated by Django 4.2.16 on 2024-11-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_response_committer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='committers',
            field=models.ManyToManyField(through='survey.ProjectCommitter', to='survey.committer'),
        ),
    ]
