# Generated by Django 4.2.16 on 2024-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_project_committers'),
    ]

    operations = [
        migrations.AddField(
            model_name='committer',
            name='projects',
            field=models.ManyToManyField(through='survey.ProjectCommitter', to='survey.project'),
        ),
    ]
