# Generated by Django 4.2.16 on 2024-11-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_committer_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcommitter',
            name='initial_commit',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.commit'),
        ),
    ]
