# Generated by Django 4.2.16 on 2024-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_projectcommitter_initial_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='primary_language',
            field=models.CharField(editable=False, max_length=30, null=True, verbose_name='primary programming language'),
        ),
        migrations.AddField(
            model_name='project',
            name='track_changes',
            field=models.BooleanField(default=True, editable=False, verbose_name="are we tracking this project's changes?"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='typechecker_files',
            field=models.CharField(editable=False, max_length=300, null=True, verbose_name='list of typechecker configuration files detected'),
        ),
    ]
