# Generated by Django 4.2.16 on 2024-12-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_commit_author_commit_committer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('project', 'hash'), name='unique_commit_hash_in_project'),
        ),
    ]
