# Generated by Django 4.2.16 on 2024-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_commit_unique_commit_hash_in_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='track_changes',
            field=models.BooleanField(default=False, editable=False, verbose_name="are we tracking this project's changes?"),
        ),
    ]
