# Generated by Django 4.2.16 on 2024-12-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcommitter',
            name='response_tags',
            field=models.ManyToManyField(to='survey.code'),
        ),
    ]
