# Generated by Django 4.2.16 on 2024-12-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_projectcommitter_response_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='tags',
            field=models.ManyToManyField(to='survey.code'),
        ),
    ]
