# Generated by Django 4.2.16 on 2024-12-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_response_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='responses',
            field=models.ManyToManyField(to='survey.response'),
        ),
    ]
