# Generated by Django 4.2.16 on 2024-12-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_code_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='responses',
        ),
    ]
