# Generated by Django 4.2.16 on 2024-12-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_remove_code_responses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='ChangeReason',
        ),
    ]
