# Generated by Django 4.2.16 on 2024-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_rename_code_changereason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcommitter',
            name='initial_survey_response',
        ),
        migrations.AddField(
            model_name='committer',
            name='initial_survey_response',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='response to initial survey'),
        ),
        migrations.AddField(
            model_name='projectcommitter',
            name='is_maintainer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='projectcommitter',
            name='maintainer_survey_response',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='response to maintainer survey'),
        ),
    ]
