# Generated by Django 4.2.16 on 2024-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_remove_projectcommitter_initial_survey_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_host',
            field=models.CharField(editable=False, max_length=200, null=True, verbose_name='repository host'),
        ),
        migrations.AddField(
            model_name='response',
            name='committer_commits_at_time',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
