# Generated by Django 4.2.16 on 2024-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_project_repository_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='typechecker_files',
            field=models.TextField(editable=False, max_length=300, null=True, verbose_name='list of typechecker configuration files detected'),
        ),
    ]
