# Generated by Django 4.2.16 on 2024-12-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_alter_project_typechecker_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='typechecker_files',
            field=models.TextField(editable=False, null=True, verbose_name='list of typechecker configuration files detected'),
        ),
    ]
