# Generated by Django 4.2.16 on 2025-01-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_alter_project_typechecker_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='committer',
            name='removal',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date of removal request & processing'),
        ),
    ]
