# Generated by Django 4.2.16 on 2025-01-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_committer_removal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
    ]
