# Generated by Django 4.2.16 on 2025-02-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(editable=False, max_length=200, verbose_name='Host Name')),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('hostname',), name='unique_node_names'),
        ),
        migrations.AddField(
            model_name='project',
            name='host_node',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.node'),
        ),
    ]
