# Generated by Django 4.2.16 on 2025-02-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_data_repository_host_to_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repository_host',
        ),
    ]
