# Generated by Django 4.2.16 on 2025-02-12 16:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_remove_project_repository_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=markdownx.models.MarkdownxField(verbose_name='Frequently Asked Question'),
        ),
    ]
