# Generated by Django 4.2.16 on 2025-02-12 16:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_alter_faq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
