# Generated by Django 4.2.16 on 2025-02-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-weight',)},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('hostname',)},
        ),
    ]
