# Generated by Django 4.2.16 on 2025-02-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_initialresponsecode_committer_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitialResponseCode',
            new_name='InitialReason',
        ),
    ]
