# Generated by Django 4.2.16 on 2025-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('survey', '0034_remove_projectcommitter_response_tags'), ('survey', '0035_maintainerreason'), ('survey', '0036_projectcommitter_tags')]

    dependencies = [
        ('survey', '0032_initialresponsecode_committer_tags_squashed_0033_rename_initialresponsecode_initialreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcommitter',
            name='response_tags',
        ),
        migrations.CreateModel(
            name='MaintainerReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectcommitter',
            name='tags',
            field=models.ManyToManyField(to='survey.maintainerreason'),
        ),
    ]
