# Generated by Django 4.2.16 on 2025-02-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_initialresponsecode_committer_tags_squashed_0033_rename_initialresponsecode_initialreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcommitter',
            name='response_tags',
        ),
    ]
