# Generated by Django 4.2.16 on 2025-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_maintainerreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcommitter',
            name='tags',
            field=models.ManyToManyField(to='survey.maintainerreason'),
        ),
    ]
