# Generated by Django 4.2.16 on 2025-02-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_remove_projectcommitter_response_tags_squashed_0036_projectcommitter_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changereason',
            options={'verbose_name': 'Reason for Change'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-weight',), 'verbose_name': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='initialreason',
            options={'verbose_name': 'Initial Response Code'},
        ),
        migrations.AlterModelOptions(
            name='maintainerreason',
            options={'verbose_name': 'Maintainer Response Codes'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('hostname',), 'verbose_name': 'Worker Node'},
        ),
        migrations.AlterModelOptions(
            name='projectcommitter',
            options={'verbose_name': 'Project Committer'},
        ),
    ]
