# Generated by Django 4.2.16 on 2025-02-12 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_alter_changereason_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 12, 19, 22, 43, 199214, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
