# Generated by Django 4.2.16 on 2025-02-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_commit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
