# Generated by Django 4.2.16 on 2025-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_node_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
