# Generated by Django 4.2.16 on 2025-02-12 20:12

from django.db import migrations

def create_vacuum_task(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    schedule, created = IntervalSchedule.objects.get_or_create(every = 1, period = 'hours')
    if created:
        schedule.save()
    task = PeriodicTask(interval = schedule, name='Vacuum Irrelevant Commits', task = 'survey.periodic_tasks.vacuum_irrelevant_commits')
    task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_node_enabled'),
    ]

    operations = [
        migrations.RunPython(create_vacuum_task)
    ]
