# Generated by Django 4.2.16 on 2025-02-12 20:33

from django.db import migrations

def create_healthcheck_task(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    schedule, created = IntervalSchedule.objects.get_or_create(every=5, period='minutes')
    if created:
        schedule.save()
    task = PeriodicTask(interval=schedule, name='node_health_check', task='survey.periodic_tasks.node_health_check')
    task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_install_vacuum_task'),
    ]

    operations = [
        migrations.RunPython(create_healthcheck_task)
    ]
