# Generated by Django 4.2.16 on 2025-02-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_restructure_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.node')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deletedrepository',
            constraint=models.UniqueConstraint(fields=('node', 'project'), name='unique_deleted_repos'),
        ),
    ]
