# Generated by Django 4.2.16 on 2025-02-13 15:50

from django.db import migrations

def create_repo_cleaner(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    schedule, created = IntervalSchedule.objects.get_or_create(every=1, period='days')
    if created:
        schedule.save()
    task = PeriodicTask(interval=schedule, name='clean_deleted_repos', task='survey.tasks.periodic.clean_repos')
    task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_deletedrepository_and_more'),
    ]

    operations = [
        migrations.RunPython(create_repo_cleaner)
    ]
