# Generated by Django 4.2.16 on 2025-02-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('survey', '0046_alter_deletedrepository_options_and_more'), ('survey', '0047_alter_deletedrepository_reason')]

    dependencies = [
        ('survey', '0045_install_repo_cleaner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedrepository',
            options={'verbose_name_plural': 'Deleted Repositories'},
        ),
        migrations.RemoveConstraint(
            model_name='deletedrepository',
            name='unique_deleted_repos',
        ),
        migrations.RemoveField(
            model_name='deletedrepository',
            name='project',
        ),
        migrations.AddField(
            model_name='deletedrepository',
            name='name',
            field=models.CharField(default=None, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedrepository',
            name='owner',
            field=models.CharField(default=None, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedrepository',
            name='node',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.node'),
        ),
        migrations.AddField(
            model_name='deletedrepository',
            name='reason',
            field=models.CharField(choices=[('RB', 'Rebalance'), ('RN', 'Rename'), ('UN', 'Unused'), ('IR', 'Irrelevant'), ('MN', 'Manual')], default='RB', max_length=2),
        ),
    ]
