# Generated by Django 4.2.16 on 2025-02-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_alter_deletedrepository_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedrepository',
            name='reason',
            field=models.CharField(choices=[('RB', 'Rebalance'), ('RN', 'Rename'), ('UN', 'Unused'), ('IR', 'Irrelevant'), ('MN', 'Manual')], default='RB', max_length=2),
        ),
    ]
