# Generated by Django 4.2.16 on 2025-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_alter_deletedrepository_options_and_more_squashed_0047_alter_deletedrepository_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcommitter',
            name='has_been_emailed',
            field=models.BooleanField(null=True),
        ),
    ]
