# Generated by Django 4.2.16 on 2025-03-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_projectcommitter_has_been_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='survey.projectcommitter'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pusher', to='survey.projectcommitter'),
        ),
    ]
