# Generated by Django 4.2.16 on 2025-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_alter_commit_author_alter_commit_committer'),
    ]

    operations = [
        migrations.AddField(
            model_name='committer',
            name='consent_project_commit',
            field=models.TextField(blank=True, null=True, verbose_name='location of consent'),
        ),
    ]
