# Generated by Django 4.2.16 on 2025-04-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0050_committer_consent_project_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='relevance_type',
            field=models.CharField(choices=[('IR', 'Irrelevant'), ('AD', 'Added'), ('RM', 'Removed'), ('CH', 'Changed')], default='IR', max_length=2),
        ),
    ]
