# Generated by Django 4.2.16 on 2025-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0051_commit_relevance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcommitter',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='projectcommitter',
            name='has_been_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
