# Generated by Django 4.2.16 on 2025-04-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0052_projectcommitter_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcommitter',
            name='email_address',
        ),
        migrations.AddField(
            model_name='committer',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
