# Generated by Django 4.2.16 on 2025-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0053_remove_projectcommitter_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedrepository',
            name='reason',
            field=models.CharField(choices=[('RB', 'Rebalance'), ('RN', 'Rename'), ('UN', 'Unused'), ('IR', 'Irrelevant'), ('MN', 'Manual'), ('DE', 'Deleted')], default='RB', max_length=2),
        ),
    ]
