# Generated by Django 4.2.16 on 2025-04-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0054_alter_deletedrepository_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='committer',
            name='name',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
