# Generated by Django 4.2.16 on 2025-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0055_committer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintainerreason',
            options={'verbose_name': 'Maintainer Response Code'},
        ),
        migrations.AddField(
            model_name='project',
            name='data_sub_directory',
            field=models.CharField(editable=False, max_length=200, null=True, verbose_name='data subdirectory'),
        ),
    ]
