# Generated by Django 4.2.16 on 2025-04-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0056_alter_maintainerreason_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='use_datadir_subdirs',
            field=models.BooleanField(default=False),
        ),
    ]
