# Generated by Django 4.2.16 on 2025-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0057_node_use_datadir_subdirs'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedrepository',
            name='subdir',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
