# Generated by Django 4.2.16 on 2025-04-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0058_deletedrepository_subdir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='data_sub_directory',
            new_name='data_subdir',
        ),
    ]
