# Generated by Django 4.2.16 on 2025-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0059_rename_data_sub_directory_project_data_subdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotations_detected',
            field=models.BooleanField(default=False, editable=False, verbose_name='Have annotations been detected?'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_typechecker_configuration',
            field=models.BooleanField(default=False, editable=False, verbose_name='Does the project have type checker configuration?'),
        ),
    ]
