# Generated by Django 4.2.16 on 2025-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0060_project_annotations_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('TS', 'TypeScript'), ('RB', 'Ruby'), ('PH', 'PHP'), ('RL', 'GNU R')], default='PY', max_length=2, verbose_name='Primary programming language'),
        ),
    ]
