# Generated by Django 4.2.16 on 2025-04-14 19:17

from django.db import migrations

def update_primary_language_to_language(apps, schema_editor):
    Project = apps.get_model("survey", "Project")
    for project in Project.objects.all():
        lang = project.primary_language.lower()
        if lang == 'python':
            project.language = 'PY'
        elif lang == 'typescript':
            project.language = 'TS'
        elif lang == "Ruby":
            project.language = 'RB'
        elif lang == "R":
            project.language = 'RL'
        elif lang == "PHP":
            project.language = 'PH'

        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0061_project_language'),
    ]

    operations = [
        migrations.RunPython(update_primary_language_to_language)
    ]
