# Generated by Django 4.2.16 on 2025-04-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0062_primary_language_to_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='primary_language',
        ),
    ]
