# Generated by Django 4.2.16 on 2025-04-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0063_remove_project_primary_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committer',
            name='consent_project_commit',
            field=models.TextField(blank=True, null=True, verbose_name='consent location'),
        ),
        migrations.AlterField(
            model_name='committer',
            name='consent_timestamp',
            field=models.DateTimeField(editable=False, null=True, verbose_name='consent date'),
        ),
        migrations.AlterField(
            model_name='committer',
            name='initial_contact_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='first contact'),
        ),
        migrations.AlterField(
            model_name='committer',
            name='initial_survey_response',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='initial survey response'),
        ),
        migrations.AlterField(
            model_name='committer',
            name='last_contact_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last contact'),
        ),
        migrations.AlterField(
            model_name='committer',
            name='opt_out',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='opt-out date'),
        ),
        migrations.AlterField(
            model_name='committer',
            name='removal',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='removal date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='add date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='annotations_detected',
            field=models.BooleanField(default=False, editable=False, verbose_name='annotations detected?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_typechecker_configuration',
            field=models.BooleanField(default=False, editable=False, verbose_name='has typechecker config?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('TS', 'TypeScript'), ('RB', 'Ruby'), ('PH', 'PHP'), ('RL', 'GNU R')], default='PY', max_length=2, verbose_name='primary language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(editable=False, max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(editable=False, max_length=200, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='remove_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='remove date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='track_changes',
            field=models.BooleanField(default=False, editable=False, verbose_name='tracking?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='typechecker_files',
            field=models.TextField(editable=False, null=True, verbose_name='typchecker files detected'),
        ),
    ]
