# Generated by Django 4.2.16 on 2025-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0064_alter_committer_consent_project_commit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_language_files',
            field=models.BooleanField(default=False, editable=False, verbose_name='has files in the language?'),
        ),
    ]
