# Generated by Django 4.2.16 on 2025-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0065_project_has_language_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcommitter',
            name='has_been_emailed',
        ),
        migrations.AddField(
            model_name='committer',
            name='has_been_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
