# Generated by Django 4.2.16 on 2025-04-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0066_remove_projectcommitter_has_been_emailed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
