# Generated by Django 4.2.16 on 2025-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0067_faq_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='committer',
            name='initial_contact_location',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Location of initial contact'),
        ),
    ]
