# Generated by Django 4.2.16 on 2025-06-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0069_alter_commit_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='relevant_change_file',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='relevant_change_line',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
