# Generated by Django 4.2.16 on 2025-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0070_commit_relevant_change_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='json_data',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
