# Generated by Django 4.2.18 on 2025-07-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0071_commit_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='tags',
            field=models.ManyToManyField(related_name='responses', to='survey.changereason'),
        ),
    ]
