# Generated by Django 4.2.18 on 2025-07-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0072_alter_response_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metrics_collected',
            field=models.BooleanField(default=False, editable=False, verbose_name='metrics collected?'),
        ),
        migrations.CreateModel(
            name='MetricsCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(editable=False, max_length=40)),
                ('relevance_type', models.CharField(choices=[('IR', 'Irrelevant'), ('AD', 'Added'), ('RM', 'Removed'), ('CH', 'Changed')], default='IR', max_length=2)),
                ('relevant_change_file', models.TextField(blank=True, editable=False, null=True)),
                ('relevant_change_line', models.IntegerField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(editable=False, max_length=200)),
                ('committer', models.CharField(editable=False, max_length=200)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='metricscommit',
            constraint=models.UniqueConstraint(fields=('project', 'hash'), name='unique_metricscommit_hash_in_project'),
        ),
    ]
