# Generated by Django 4.2.16 on 2025-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0074_alter_changereason_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_commits',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
