# Generated by Django 4.2.16 on 2025-07-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0075_project_num_commits'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_committers',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
