# Generated by Django 4.2.16 on 2025-12-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0076_project_num_committers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='had_installation',
            field=models.BooleanField(default=False, editable=False, verbose_name='Was the project ever installed?'),
        ),
    ]
